version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wildguard-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NASA_FIRMS_API_KEY=${NASA_FIRMS_API_KEY}
      - AI_STUDIO_API_KEY=${AI_STUDIO_API_KEY}
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static
      - ./backend/uploads:/app/uploads
    networks:
      - wildguard-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wildguard-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - wildguard-network

networks:
  wildguard-network:
    driver: bridge
